apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest
spec:
  replicas: 3  # Número inicial de réplicas
  selector:
    matchLabels:
      app: api-rest
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
        - name: api-rest
          image: php-api-rest-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"  #mínimo 0.25 cpu
              memory: "512Mi"
            limits:
              cpu: "500m" #máximo 0.5 cpu
              memory: "1Gi"