apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Balanceador de carga 
